### ISSUE TITLE
イラスト納品

### ISSUE THREAD

**Issue by fruitsnoodle** [o2project/start-dash-of-site-making#10]
7月下旬ぐらい納品予定

**Comment by kubosho** [comment]
@fruitsnoodle 
表紙イラスト納品いつくらいになるか追記してください。

**Comment by kubosho** [comment]
確認して戻しもあるかもしれないので、できれば 11/15 までには欲しいところ…
(最悪 11/20)

**Comment by kubosho** [comment]
@fruitsnoodle 
イラストOKです！
