### ISSUE TITLE
[ch1] 「要件定義」について

### ISSUE THREAD

**Issue by momdo** [o2project/start-dash-of-site-making#103]
issueを立てた私も実務のサイト経験が無いので実はよく分かってないのですが、一般に要求定義とはどういったものなのか？という定義があった方がよいのではないでしょうか。

たとえば、e-words.jpでは、
http://e-words.jp/w/%E8%A6%81%E4%BB%B6%E5%AE%9A%E7%BE%A9.html

> 要件定義とは、システムやソフトウェアの開発において、実装すべき機能や満たすべき性能などのを明確にしていく作業のこと。いわゆる上流工程の一部で、実際の開発・実装作業を始める前に行う作業の一つである。
> 要件定義では、利用者がそのシステムなどで何がしたいのかを元に、それを実現するために実装しなければならない機能や、達成しなければならない性能などを開発者が検討して明確にしていく。まとめられた成果は「要件定義書」として文書化されることが多い。一般的にこの段階では「何が」必要なのかを定義するに留め、それを「どのように」設計・実装すべきかは後の工程で検討される。
> 要件定義に先立って、利用者が業務を進める際に、そのシステムなどを使って何がしたいのか、何ができなければ困るのかといった内容を聞き取ってまとめる作業を「要求定義」というが、要件定義と要求定義を同義とする立場もあり、その場合は、このような利用者からの要求をまとめる作業も要件定義に含まれる。

というような説明がありますが、これが最初に挙げられる

> どんなWebサイトを作るか
> どんな機能が必要か

とどう結びつくのか、というのが若干薄いように感じました（あくまで私見です）。

**Comment by fruitsnoodle** [comment]
@momdo 
レビューありがとうございます！

> 要件定義では、利用者がそのシステムなどで何がしたいのかを元に、それを実現するために実装しなければならない機能や、達成しなければならない性能などを開発者が検討して明確にしていく。
> 一般的にこの段階では「何が」必要なのかを定義するに留め、それを「どのように」設計・実装すべきかは後の工程で検討される。

主の上記内容をすごく直な表現にしただけです。
何故かと言うとターゲット読者は「趣味があってサイト作ってみよう」という層です。ここではなるべく難しいことを読ませずに、楽しくスキルだけ身につけて欲しいです。

**Comment by momdo** [comment]
@fruitsnoodle さま
早速のコメントありがとうございます。確かに、定義を持ち出すのは気軽にサイトを作成するにはちょっと難しいですね。

そうすると、おっしゃるように「趣味があってサイト作ってみよう」という層に対して、「要件定義」という言葉自体が難しいのではないでしょうか？たとえば、「Webサイトに必要なものを挙げてみる」というようなタイトルでもよいはずです（あくまで一例ですが、この方がフレンドリーな見出しだと思います）。

**Comment by kubosho** [comment]
@momdo 
相談した結果「要件定義」という言葉は使うことにして、具体的にどんなことをするのかという例を書く流れになりました。

たとえばLIGのこの記事で書かれている例です。

【新人ディレクター向け vol.5】Web制作における要件定義で心がける5つのポイント | 株式会社LIG
http://liginc.co.jp/web/useful/160462

> 例
> ディレクター：どんなサービスを作りたいのですか？
> クライアント：住宅が少しでも早く探せるサービスですね。
> ディレクター：ほうほう、少しでも早くと言うと？
> クライアント：チャット機能とかあって相談できたら便利じゃないですか？
> ディレクター：確かにそうですね。チャット使うなら会員機能も必要ですか？
> クライアント：そうですね、そこは必須ですね。
> とこんなやり取りをしながら、どんなシステム・サービスにしていくか、クライアントの要求を定義していく工程のことです。

**Comment by momdo** [comment]
@kubosho さま
それで大丈夫と思います（今のままだと少し説明が足りないように感じたので）。

**Comment by kubosho** [comment]
@fruitsnoodle 曰く
こんな感じで書く予定です。

---

「要件定義」という言葉をウェブ上で検索して、すごくプロフェッショナルな解釈が出てきて、それで「大変だ！」と思う方もいると思います。

> 要件定義とは、システムやソフトウェアの開発において、実装すべき機能や満たすべき性能などのを明確にしていく作業のこと。いわゆる上流工程の一部で、実際の開発・実装作業を始める前に行う作業の一つである。
> 要件定義では、利用者がそのシステムなどで何がしたいのかを元に、それを実現するために実装しなければならない機能や、達成しなければならない性能などを開発者が検討して明確にしていく。まとめられた成果は「要件定義書」として文書化されることが多い。
> 引用元：IT用語辞典（http://e-words.jp/w/要件定義.html）

実際やる時は、そこまで大変ではありません。

下記の2ポイントを把握できれば、「要件定義」がスムーズに行われます。
- どんなWebサイトを作るか
- どんな機能が必要か

下記のように自問自答すれば、答えを導くことができます。

> 質問：どんなサイトを作りたいですか。
> 回答：「ラブライブ！」というイベントの情報を発信するサイトを作りたいです。
> 質問：どんな情報を発信したいですか。
> 回答：イベントの開催日、参加者、またはチケット情報などを発信したいです。また、現場にこれない方がネットでライブを楽しめる機能あったら便利です。そして、主催側としてイベントがいろんな人に知られているほうが嬉しいので、SNSなどで簡単に拡散できる機能があればうれしいです。

**Comment by kubosho** [comment]
@momdo 

@fruitsnoodle 案を元に自分のほうで文章を書いてみました。
これで要件定義についての説明は十分そうでしょうか？

https://github.com/o2project/start-dash-of-site-making/blob/master/articles/draft/ch01.md

**Comment by momdo** [comment]
説明としてはこれで十分だと思います（後の文章への接続も見通しがかなりよくなったと思います）。
ただ、個人的な意見ですが一点コメントをあえてするならば、自問自答するときには「ですます調」ですることはあまりないのかな、と思いました。

**Comment by kubosho** [comment]
確かにそうですね。
そこは口語体にしておこうと思います。
