### ISSUE TITLE
[ch2] 「ブラウザー」に関して

### ISSUE THREAD

**Issue by momdo** [o2project/start-dash-of-site-making#105]
> WindowsやOS Xには次のブラウザーが最初からインストールされています。

とありますが、直下にブラウザーが列挙されていません。また、

> しかしサイト開発ではこれらのブラウザーだけではなく、複数ブラウザーで表示を確認する必要があります。 

とありますが、（意地悪な考え方として）Windowsには最初からEdgeとInternet Explorerの両方がインストールされているわけで、この2つで複数と見なせてしまうことになります。複数とはどういうことなのかもう少し説明する必要があると思います。

**Comment by kubosho** [comment]
> 直下にブラウザーが列挙されていません

コピペミスでした…
