### ISSUE TITLE
Special thanksに載せてもいいかどうか

### ISSUE THREAD

**Issue by kubosho** [o2project/start-dash-of-site-making#107]
@momdo
@sd-ts1017 
@windyakin
@yoshiko-pg
@hiloki

issueやPull Requestを送っていただきありがとうございます。
とてもとても助かっています。

つきましては[index.md](https://github.com/o2project/start-dash-of-site-making/blob/master/draft/index.md)のSpecial thanksに名前を掲載したいのですが、3つ確認したい事項があるので、返信をお願いしたいです。
1. 名前を載せてもいいでしょうか？
2. 名前を載せてもいい場合、基本TwitterアカウントのIDを載せますがいいでしょうか？
3. （Twitterアカウント以外を希望する方は）載せたいアカウントを教えていただいていいでしょうか？

**Comment by okohs** [comment]
くい靴隋��さん

おつかれさまです！
しょこです

1.OKです
2.OKです (sd_ts1017)
3.-

よろしくお願いしますっ

iPhoneから送信

2015/12/16 1:45$B!"(BShota Kubota notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by yoshiko-pg** [comment]
もちろん大丈夫ですよー！Twitterアカウントでお願いします！

**Comment by windyakin** [comment]
大丈夫です :+1:

**Comment by hiloki** [comment]
All OKです :+1:

**Comment by momdo** [comment]
大丈夫です。（Twitterアカウントはアンダーバーをお忘れなく。）
