### ISSUE TITLE
[ch1] (draft)ラブライブの表記揺れ

### ISSUE THREAD

**Issue by momdo** [o2project/start-dash-of-site-making#114]
少なくとも、
https://github.com/o2project/start-dash-of-site-making/blob/master/articles/draft/ch01.md
でラブライブ!とラブライブ！の表記が混在しているようです（感嘆符が半角と全角両方ある）。

**Comment by kubosho** [comment]
@momdo 
ありがとうございます。後ほど「！（全角感嘆符）」に揃えます。
