### ISSUE TITLE
[Ch2] 「分からないこと」

### ISSUE THREAD

**Issue by fruitsnoodle** [o2project/start-dash-of-site-making#25]
https://github.com/o2project/start-dash-of-site-making/blob/master/draft/ch02.md

具体的に何がわからないと想定していますか。
- 固有名詞がわからない
- やり方がわからない
- 素材を探したい
- コードがわからない
- エラーがわからない（どこで出たエラー？）

**Comment by kubosho** [comment]
素材を探したい以外の全てを想定している。
