### ISSUE TITLE
[Ch1] 「ライセンス」「著作権」

### ISSUE THREAD

**Issue by fruitsnoodle** [o2project/start-dash-of-site-making#27]
ライセンスと著作権を侵害しないように注意します。
ですが、自分は絵かけないしセンスも良くないと思われます。素材をどうしたらいいでしょうか。
という提案がほしいです。
- 「カラー」をうまく使ってください。シンプルでセンスの良いサイトをつくろう。
- 非商用フリー素材や商用フリー素材などがあるので、使う場合は自力で探してください。

**Comment by kubosho** [comment]
@fruitsnoodle 
https://github.com/o2project/start-dash-of-site-making/blob/8e62d26f8d89f453e31350e2516274794650c3c1/draft/ch02.md#イラストや素材を自作できない場合どうしたら良いか

提案を書いてみました。確認お願いします。

**Comment by momdo** [comment]
せっかくクリエイティブコモンズでこの一連の文章が公開するわけですから、著作権の項でクリエイティブコモンズに触れても良いのではないでしょうか。

**Comment by kubosho** [comment]
@momdo 
確かにそうですね。クリエイティブ・コモンズについても触れようと思います。
