### ISSUE TITLE
[Ch1] ワイヤーフレームのくだりでの文章表現

### ISSUE THREAD

**Issue by hiloki** [o2project/start-dash-of-site-making#48]
> なぜなら、デザイナはグラフィックと UI の制作に、参考資料としてワイヤーフレームを使うためです。そのため、余計な情報があると資料は分かりづらくなり、混乱を招くことにあります。

混乱を招くことにあります。
↓
（資料は ...）混乱を招きます。

でしょうか、どうでしょう？

**Comment by kubosho** [comment]
@hiloki 
良さそうです。提案の通りに書きかえます。
