### ISSUE TITLE
[ch3] 冗長なARIAロール

### ISSUE THREAD

**Issue by momdo** [o2project/start-dash-of-site-making#58]
ARIA in HTML仕様の1章によれば、
http://momdo.github.io/html-aria/#rules-wd

<blockquote>
<p>著者は、強いネイティヴセマンティックと衝突するまたは与えられるHTML要素のデフォルトの暗黙のARIAセマンティックと等価である場合を除いた、[wai-aria-1.1]で説明される要求にしたがって、HTML要素のARIA roleおよびaria-*属性を使用してもよい。<br>
（中略）<br>
ウェブ開発者は、表に定義されるデフォルトの暗黙のARIAセマンティックと一致する値にARIA roleおよびaria-*属性を設定すべきでない。
</blockquote>

とされますので、3.5節 ナビゲーション部分のマークアップで説明されているように<code>nav</code>要素に<code>role="navigation"</code>を設定するのは、すべきではありません（SHOULD NOT）。

もし記述するのであれば、3.6節でIE11のために<code>main</code>要素に<code>role="main"</code>を設定するような理由が必要になると思います。

**Comment by kubosho** [comment]
確かに仕様にもそう書かれていますね。なぜ付けてしまったのか…
