### ISSUE TITLE
[ch3] 最新のHTML5.1草案で、role=mainを推奨する記述は削除されている

### ISSUE THREAD

**Issue by momdo** [o2project/start-dash-of-site-making#77]
関連： #58

HTML5.1の日本語訳が古いのが原因ではありますが、最新のHTML5.1仕様で、`role=main`を推奨する記述はありません（4つ目の注がない）。
参照：http://www.w3.org/TR/2015/WD-html51-20151008/semantics.html#the-main-element

**Comment by kubosho** [comment]
@momdo 
ありがとうございます。
第3章ですが、いま手元で大幅に書き換えていて、その辺りの記述が無くなる予定です。
ただHTMLによるマークアップの例はあるので、そのコード例から`role="main"`を無くす形で対応します。

**Comment by momdo** [comment]
了解です。
こちらもHTML5.1日本語訳自身の日付が古いことをあまり告知してなかった気もするので、訳自身をどうするのかも含めて検討します。
