### ISSUE TITLE
[Ch5] 「次に」を多用しすぎている

### ISSUE THREAD

**Issue by kubosho** [o2project/start-dash-of-site-making#92]
- 一つのまとまった文章に見えてしまう
- 文章として稚拙な印象を受ける

ので何とかする

**Comment by momdo** [comment]
回避策(1)「次に」を以下の語彙で言い換えてみるのはどうでしょう。文脈に応じて、好きなのを持っていってください：

-それから
-続いて
-加えて
-さらに
-また

回避策(2)「最初に」「次に」「最後に」という文章のフレームを変える：
「最初にAをします。次にBをします。最後にCをします。」という文をたとえば、
「Bをする前にAをあらかじめしておきます。それから目的のCをします。」とかまあいろいろあると思います。

**Comment by kubosho** [comment]
@momdo 
提案ありがとうございます！参考にします。
